server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    link:   "mysql:root:123456@tcp(127.0.0.1:3306)/learn?loc=Local&parseTime=true"
    debug:  true

redis:
  default:
    address: 127.0.0.1:6379
    db:      1
    idleTimeout: 600
  cache:
    address:     127.0.0.1:6379
    db:          2
    idleTimeout: 600


