// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gf_demo/internal/logic/goods"
	_ "gf_demo/internal/logic/middleware"
	_ "gf_demo/internal/logic/user"
)
