// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure of table users for DAO operations like Where/Data.
type Users struct {
	g.Meta        `orm:"table:users, do:true"`
	Id            interface{} //
	Nickname      interface{} //
	Mobile        interface{} // 手机号
	ProfilePic    interface{} // 头像
	Sign          interface{} // 签名
	Fans          interface{} // 粉丝数
	Follows       interface{} // 关注数
	Passport      interface{} //
	Password      interface{} //
	RememberToken interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
