// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_demo/internal/model"
	"gf_demo/internal/model/entity"
)

type (
	IUser interface {
		Create(ctx context.Context, mobile string) error
		IsMobileExist(ctx context.Context, mobile string) (bool, error)
		GetProfile(ctx context.Context) (user *entity.User, err error)
		AuthMobileAndCode(ctx context.Context, in *model.UserLoginInput) (bool, error)
		GetUserByMobile(ctx context.Context, in *model.UserLoginInput) map[string]interface{}
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
