// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Goods is the golang structure for table goods.
type Goods struct {
	Id          uint        `json:"id"          ` //
	Name        string      `json:"name"        ` //
	Description string      `json:"description" ` //
	CreatedAt   *gtime.Time `json:"created_at"  ` //
	UpdatedAt   *gtime.Time `json:"updated_at"  ` //
}
