// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Goods is the golang structure for table goods.
type Goods struct {
	Id          uint        `json:"Id"          ` //
	Name        string      `json:"Name"        ` //
	Description string      `json:"Description" ` //
	CreatedAt   *gtime.Time `json:"CreatedAt"   ` //
	UpdatedAt   *gtime.Time `json:"UpdatedAt"   ` //
}
