// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserInfo is the golang structure for table user_info.
type UserInfo struct {
	UserId   uint   `json:"UserId"   ` //
	Nickname string `json:"Nickname" ` //
	Avatar   string `json:"Avatar"   ` //
	Type     uint   `json:"Type"     ` //
	Sex      uint   `json:"Sex"      ` //
}
