// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	UserId        uint        `json:"user_id"        ` //
	Nickname      string      `json:"nickname"       ` //
	Mobile        string      `json:"mobile"         ` // 手机号
	Passport      string      `json:"passport"       ` //
	Password      string      `json:"password"       ` //
	RememberToken string      `json:"remember_token" ` //
	CreatedAt     *gtime.Time `json:"created_at"     ` //
	UpdatedAt     *gtime.Time `json:"updated_at"     ` //
}
