// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserInfo is the golang structure for table user_info.
type UserInfo struct {
	UserId   uint   `json:"user_id"  ` //
	Nickname string `json:"nickname" ` //
	Avatar   string `json:"avatar"   ` //
	Type     uint   `json:"type"     ` //
	Sex      uint   `json:"sex"      ` //
}
