// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
	Id            uint        `json:"Id"            ` //
	Nickname      string      `json:"Nickname"      ` //
	Mobile        string      `json:"Mobile"        ` // 手机号
	ProfilePic    string      `json:"ProfilePic"    ` // 头像
	Sign          string      `json:"Sign"          ` // 签名
	Fans          uint        `json:"Fans"          ` // 粉丝数
	Follows       uint        `json:"Follows"       ` // 关注数
	Passport      string      `json:"Passport"      ` //
	Password      string      `json:"Password"      ` //
	RememberToken string      `json:"RememberToken" ` //
	CreatedAt     *gtime.Time `json:"CreatedAt"     ` //
	UpdatedAt     *gtime.Time `json:"UpdatedAt"     ` //
}
