// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	UserId        uint        `json:"UserId"        ` //
	Nickname      string      `json:"Nickname"      ` //
	Mobile        string      `json:"Mobile"        ` // 手机号
	Passport      string      `json:"Passport"      ` //
	Password      string      `json:"Password"      ` //
	RememberToken string      `json:"RememberToken" ` //
	CreatedAt     *gtime.Time `json:"CreatedAt"     ` //
	UpdatedAt     *gtime.Time `json:"UpdatedAt"     ` //
}
